[2024-04-24 20:54:59] Ocorreu um erro:
exceptions must derive from BaseException
Traceback (most recent call last):
  File "E:\adeld\PythonProjects\ldm_algoritmo_genetico\src\versions\version_01.py", line 15, in version_01
    algorithm.init()
  File "E:\adeld\PythonProjects\ldm_algoritmo_genetico\src\model\GeneticAlgorithm.py", line 217, in init
    self.check_individual_best()
  File "E:\adeld\PythonProjects\ldm_algoritmo_genetico\src\model\GeneticAlgorithm.py", line 145, in check_individual_best
    self.save_doc(pos_best, max_fit, min_fit, avg)
  File "E:\adeld\PythonProjects\ldm_algoritmo_genetico\src\model\GeneticAlgorithm.py", line 192, in save_doc
    with open('base.html', 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'base.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\adeld\PythonProjects\ldm_algoritmo_genetico\src\main.py", line 12, in main
    version_01()
  File "E:\adeld\PythonProjects\ldm_algoritmo_genetico\src\versions\version_01.py", line 18, in version_01
    raise f'Erro na execução da versão 01:\n{e}\n'
TypeError: exceptions must derive from BaseException
